In [93]:
import string 
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model
from sklearn import pipeline
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [94]:
eng_df=pd.read_csv("/content/English.txt","utf-8", header=None, names=["English"])
eng_df.tail()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


English
1495  BBC News Services
1496     On your mobile
1497  On smart speakers
1498    Get news alerts
1499   Contact BBC News

In [95]:
french_df=pd.read_csv("/content/french.txt","utf-8", header=None, names=["French"])
french_df.head ()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


French
0  Si vous disposez d'ouvrages ou d'articles de r...
1                     Comment ajouter mes sources ?
2  Cette page ou section est en train d'être tra...
3  Vous pouvez aider au développement de Wikipé...
4  Le mot nature est un terme polysémique (c’e...

In [96]:
german_df=pd.read_csv("/content/german.txt","utf-8", header=None, names=["German"])
german_df.head ()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


German
0  .Wir sind alle auf der Suche nach schnellen We...
1  Ich weiß, ich verstehe, was passiert, ist, da...
2                         Wie wäre es also mit uns?
3  Lernen Sie einige intelligente neue englische ...
4  Also werden wir heute 10 neue intelligente Wö...

In [97]:
for char in string.punctuation:
  print(char, end =" ")
punc_rem = dict((ord(char), None) for char in string.punctuation)


! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [98]:
data_eng=[]
lang_eng=[]
data_french=[]
lang_french=[]
data_german=[]
lang_german=[]

In [99]:
for i,line in eng_df.iterrows():
  line= line['English']
  if len(line)!=0:
    line= line.lower()
    line= re.sub(r"\d+","",line)
    line = line.translate(punc_rem)
    data_eng.append(line)
    lang_eng.append("English")

In [100]:
for i,line in french_df.iterrows():
  line= line['French']
  if len(line)!=0:
    line= line.lower()
    line= re.sub(r"\d+","",line)
    line = line.translate(punc_rem)
    data_french.append(line)
    lang_french.append("French")

In [101]:
for i,line in german_df.iterrows():
  line= line['German']
  if len(line)!=0:
    line= line.lower()
    line= re.sub(r"\d+","",line)
    line = line.translate(punc_rem)
    data_german.append(line)
    lang_german.append("German")

In [102]:
df= pd.DataFrame({"Text":data_eng+data_german+data_french,
                  "Language":lang_eng+lang_german+lang_french})
print(df.shape)
print(df)


(3214, 2)
                                                   Text Language
0     nature in the broadest sense is the natural ph...  English
1     nature can refer to the phenomena of the physi...  English
2     the study of nature is a large if not the only...  English
3     although humans are part of nature human activ...  English
4      the word nature is borrowed from the old fren...  English
...                                                 ...      ...
3209  une conspiration des pleutres ne cesse de déno...   French
3210  contrairement aux auditions de la commission d...   French
3211  lire aussi  article réservé à nos abonnés « l’...   French
3212  dans les etats du nevada du texas du michigan ...   French
3213  certes tout n’est pas encore joué qui sait si ...   French

[3214 rows x 2 columns]


In [103]:
X, y = df.iloc[:,0], df.iloc[:,1]
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [104]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(2571,)
(643,)
(2571,)
(643,)


In [105]:
vectorizer= feature_extraction.text.TfidfVectorizer(ngram_range=(1,3),analyzer='char')
pipe_line=pipeline.Pipeline([('vectorizer',vectorizer),('clf',linear_model.LogisticRegression())])

In [106]:
pipe_line.fit(X_train,y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [107]:
y_predicted= pipe_line.predict(X_test)

In [108]:
accurac=(metrics.accuracy_score(y_test,y_predicted))*100
print(accurac,'%')

98.28926905132192 %


In [109]:
matrix= metrics.confusion_matrix(y_test,y_predicted)
print('confusion matrix\n',matrix)

confusion matrix
 [[309   1   3]
 [  4 216   1]
 [  2   0 107]]


In [110]:
import pickle 
pick_model = open('model.pckl','wb')
pickle.dump(pipe_line,pick_model)
pick_model.close()

In [114]:
def lang_detection(text):
  punc_rem = dict((ord(char),None)for char in string.punctuation)
  global lrLanguageDetectModel
  file_model = open('/content/model.pckl','rb')
  model_detect= pickle.load(file_model)
  file_model.close()

  text = " ".join(text.split())
  text = text.lower()
  text = re.sub(r"\d+","",text)
  text = text.translate(punc_rem)
  pred = model_detect.predict([text])
  prob = model_detect.predict_proba([text])
  print(prob)
  return pred[0]
  
  

In [115]:
lang_detection("Sprechen Sie Englisch?")


[[0.05508016 0.05080345 0.89411639]]


'German'